import { useState } from "react";
import { Inter } from "next/font/google";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Toaster, toast } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [theme, setTheme] = useState<string>("");

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const response = await toast.promise(
      fetch("/api/docs", {
        method: "POST",
        body: JSON.stringify({ theme }),
        headers: {
          "Content-Type": "application/json",
        },
      }),
      {
        loading: "⏳ Generando documento...",
        success: <b>Generado</b>,
        error: <b>Could not save.</b>,
      }
    );

    const blob = await response.blob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${theme}.pdf`;
    link.click();
  };

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setTheme(event.target.value);
  };

  return (
    <>
      <Head>
        <title>Docs-gpt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>Docs-GPT</h1>
        <form className={styles.form} onSubmit={handleSubmit}>
          <label>Tema:</label>
          <input
            type="text"
            placeholder="Mecánica cuántica"
            value={theme}
            onChange={handleChange}
          />
          <button className={styles.button} type="submit">
            Generar
          </button>
        </form>
      </main>
      <Toaster />
    </>
  );
}
